### PR TITLE
Change path separator to make the firmeware project compilable on mac

### PR DESCRIPTION
**Pull request by mgeramb**
Thank you @mumpf  for this project!

This PR makes the sensor firmware project compilable on mac and linux systems by changing the path separator to / which is also fine for windows. 
Unfortunately, I do not know how the knx-dev-setup.pdf setup is created out of the .md file. But it should be also updated.

### CODE REVIEW

**Comment by mumpf** [comment]
Hi,

thank you for the pull request. I will accept this and change also the path seperator in my other projects. But are you aware, that you need to create a knxprod for this project, and this works only with an ETS installed? Or are you able to create a knxprod on a mac? If yes, please tell me how.

Regards, 
Waldemar

**Comment by mumpf** [comment]
Additional info for you: The pdf generated from md-file will be removed soon. I introdued it only due to the facht, that github did not show all screenshots I referenced in md-file. This problem is solved now, so there is no need for the pdf anymore.

**Comment by mumpf** [comment]
Finals remark: This project will depricate soon and will be continued within the OpenKNX project. I will add an according info to the readme.md as soon as the followup project can be consumed.

Regards,
Waldemar

**Comment by mgeramb** [comment]
I tried it, but it fails in the signing process, a dependend dll of the framework is missing. I expect that this is because the ETS libs are not compiled against .NET Core. Other option, like new worked on Mac.

Another problem, not related to Mac, which I saw was, that the requiered signing dll of ETS is not available in all version dirs under CV in ETS 6. So not all versions can be used. Maybe the existance should be checked to provide a better error message.

**Pull request merged**
